server:
  port: 8080

spring:
  application:
    name: rms-backend
  
  datasource:
    # Đảm bảo bạn đã chạy script SQL để tạo DB 'rms_ultimate_db' trước
    url: jdbc:mysql://localhost:3306/rms_ultimate_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: nhoklam271
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate # An toàn: Kiểm tra code khớp với DB
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Ho_Chi_Minh

jwt:
  # Đã thay bằng key dài hơn để không bị lỗi HS512 WeakKeyException
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A7134743777217A25432A462D4A614E635266556A586E3272
  expiration: 86400000

logging:
  level:
    root: INFO
    com.company.rms: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE